services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: products
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:




#  springboot-app:
#    image: product-service:latest
#    container_name: product-service-app
#    depends_on:
#      - mongodb
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/products
#    build:
#      context: .
#      dockerfile: Dockerfile